Lekkerbek.Web/Models/Bestelling.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Lekkerbek.Web.Context;
using Lekkerbek.Web.Models.Identity;
using Microsoft.EntityFrameworkCore;

namespace Lekkerbek.Web.Models
{
    public class Bestelling
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity), Key]
        public int Id { get; set; }

        public DateTime Levertijd { get; set; } = new DateTime();
        public string Opmerkingen { get; set; }= "";
        [Required]
        public ICollection<Gerecht> GerechtenLijst { get; set; }
        [Required]
        [Range(1, 999)]
        public int AantalMaaltijden { get; set; }
        [Required]
        public int KlantId { get; set; }
        public virtual Gebruiker Klant { get; set; }
        [Required]
        public Tijdslot Tijdslot { get; set; }
        public bool IsAfgerond { get; set; } = false;
        public bool IsAfhaling { get; set; } = false;
    }
}

Lekkerbek.Web/ViewModels/Bestelling/CreateViewModel.cs
using Lekkerbek.Web.Models;
using Lekkerbek.Web.Models.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lekkerbek.Web.ViewModels.Bestelling
{
    [NotMapped]
    public class CreateViewModel
    {
        //public List<Gebruiker> Klanten { get; set; }
        public IEnumerable<SelectListItem> KlantenLijst { get; set; }
        public int KlantId { get; set; }
        public IEnumerable<SelectListItem> GerechtenLijst { get; set; }
        [Required]
        [DisplayName("Aantal maaltijden")]
        public IEnumerable<string> GerechtenNamen { get; set; }
        public IEnumerable<SelectListItem> Tijdsloten{ get; set; }
        public DateTime Tijdstip{ get; set; }
        [Range(1, 999)]
        public int AantalMaaltijden { get; set; }
        public string Opmerkingen { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Bestelling/EditViewModel.cs
using Lekkerbek.Web.Models;
using Lekkerbek.Web.Models.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lekkerbek.Web.ViewModels.Bestelling
{
    [NotMapped]
    public class EditViewModel
    {
        public Gebruiker HuidigeKlant { get; set; }
        public IEnumerable<SelectListItem> Klanten { get; set; }
        public int KlantId { get; set; }
        public List<Gerecht> AlleGerechtNamen { get; set; }
        public IEnumerable<SelectListItem> Tijdslot{ get; set; }
        public Lekkerbek.Web.Models.Bestelling bestelling { get; set; }
    }
}

Lekkerbek.Web/ViewModels/Bestelling/VerwijdeGerechtViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lekkerbek.Web.ViewModels.Bestelling
{
    [NotMapped]
    public class VerwijdeGerechtViewModel
    {
    }
}

Lekkerbek.Web/ViewModels/Bestelling/VoegGerechtenToeViewModel.cs
using Lekkerbek.Web.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lekkerbek.Web.ViewModels.Bestelling
{
    [NotMapped]
    public class VoegGerechtenToeViewModel
    {
    
        public int Id { get; set; }
        public IEnumerable<SelectListItem> GerechtenLijst { get; set; }

        public string ToeTeVoegenGerecht { get; set; }
    
    }



    



}

Lekkerbek.Web/ViewModels/Bestelling/WijzigTijdslotViewModel.cs
using Lekkerbek.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lekkerbek.Web.ViewModels.Bestelling
{
    [NotMapped]
    public class WijzigTijdslotViewModel
    {
        public int Id { get; set; }
        public int NieuwTijdslotId { get; set; }
        public Tijdslot HuidigTijdslot { get; set; }
        public int HuidigTijdslotId { get; set; }
    }
}

Lekkerbek.Web/Controllers/BestellingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.Web.Context;
using Lekkerbek.Web.Models;
using Lekkerbek.Web.Models.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Admin,Kassamedewerker,Klant")]
    public class BestellingController : Controller
    {
        private readonly IdentityContext _context;
        private readonly RoleManager<Role> _roleManager;
        private readonly UserManager<Gebruiker> _userManager;
        public BestellingController(IdentityContext context, RoleManager<Role> roleManager, UserManager<Gebruiker> userManager)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Bestelling
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole(RollenEnum.Klant.ToString()))
            {
                var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                return View(OpenstaandeBestellingenVanKlantMetId(currentUser.Id));
            }
            else
            {
                return View(AlleBestellingen().Result);
            }
        }

        // GET: Bestelling/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (this.BestellingExists((int) id))
            {
                Bestelling bestelling = await _context.Bestellingen.Include("Klant").Include("Tijdslot").Include("GerechtenLijst").FirstAsync(bestelling1 => bestelling1.Id == id);
                bestelling.Tijdslot = await _context.Tijdslot.Include(tijdslot => tijdslot.InGebruikDoorKok)
                    .FirstAsync(tijdslot => tijdslot.Id == bestelling.Tijdslot.Id);
                ViewBag.TotaalPrijs = GerechtenTotaalPrijsAsync(bestelling, false).Result;
                ViewBag.TotaalPrijsInclBtw = GerechtenTotaalPrijsAsync(bestelling, true).Result;
                return View(bestelling);
            }
            else
            {
                return NotFound();
            }
            
        }

        // GET: Bestelling/Create
        public IActionResult Create()
        {
            ViewData["Klanten"] = new SelectList(_context.GebruikersMetRolKlant(), "Id", "UserName");
            ViewData["AlleGerechtenNamen"] = new SelectList(_context.Gerechten.Include("Bestellingen").Include("VoorkeursgerechtenVanKlanten").Include("Categorie"), "Naam", "Naam");
            ViewData["Tijdslot"] = new SelectList(_context.AlleVrijeTijdsloten().Result.Where(tijdslot => tijdslot.IsVrij), "Tijdstip", "Tijdstip");
            return View();
        }

        // POST: Bestelling/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection collection)
        {
            try
            {
                var tijdslot = _context.AlleVrijeTijdsloten()
                    .Result.Find(tijdslot => tijdslot.Tijdstip == DateTime.Parse(collection["Tijdslot"]));
                tijdslot.IsVrij = false;
                Gebruiker klantVanBestelling = await _userManager.GetUserAsync(User);
                Bestelling bestelling = new Bestelling()
                {
                    AantalMaaltijden = Int32.Parse(collection["AantalMaaltijden"]),
                    GerechtenLijst = new List<Gerecht>(),
                    Opmerkingen = collection["Opmerkingen"],
                    Levertijd = DateTime.Parse(collection["Levertijd"]),                    
                    Tijdslot = tijdslot
                };
                IEnumerable<string> gerechtNamen = (ICollection<string>)collection["GerechtenLijst"];
                bestelling.GerechtenLijst = await _context.Gerechten.Where(gerecht => gerechtNamen.Contains(gerecht.Naam)).ToListAsync();
                
                if (User.IsInRole(RollenEnum.Klant.ToString()))
                {
                    bestelling.KlantId = klantVanBestelling.Id;
                }
                else
                {
                    bestelling.KlantId = int.Parse(collection["Klant"]); 
                }
                
                _context.Bestellingen.Add(bestelling);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        public IActionResult VoegGerechtenToe(int id)
        {
            ViewData["Naam"] = new SelectList(_context.Gerechten.ToList(), "Naam", "Naam");
            return View(); 
        }

        [HttpPost]
        public async Task<IActionResult> VoegGerechtenToe(int id, IFormCollection collection)
        {
            var gerecht = await _context.Gerechten.FirstAsync(g => g.Naam.Equals(collection["Naam"])); 
            var bestelling = await _context.Bestellingen.FindAsync(id);
            if(bestelling.GerechtenLijst == null)
            {
                bestelling.GerechtenLijst = new List<Gerecht>(); 
            }
            bestelling.GerechtenLijst.Add(gerecht);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> VerwijderEenGerecht(String id, int bestellingId)
        {
            var gerecht = _context.Gerechten.Include("Categorie").First(g => g.Naam.Equals(id));
            var bestelling = _context.Bestellingen.Include("GerechtenLijst").ToList().First(b => b.Id == bestellingId);
            ViewData["bestellingId"] = bestellingId; 
            return View(gerecht);
        }
        [HttpPost]
        public async Task<IActionResult> VerwijderEenGerecht(String id, int bestellingid, IFormCollection collection)
        {
            var bestelling = _context.Bestellingen.Include("GerechtenLijst").ToList().First(b => b.Id == bestellingid);
            var gerecht = _context.Gerechten.Include("Categorie").First(g => g.Naam.Equals(id));
            bestelling.GerechtenLijst.Remove(gerecht);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index)); 
        }

        [HttpGet]
        public async Task<IActionResult> WijzigTijdslot(int id, int tijdslotId)
        {
            var huidigtijdslot = _context.Tijdslot.Find(tijdslotId); 
            var tijdsloten = _context.AlleVrijeTijdsloten();
            ViewData["HuidigTijdslot"] = huidigtijdslot.Tijdstip; 
            ViewData["Tijdslot"] = new SelectList(tijdsloten.Result, "Id", "Tijdstip"); 
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> WijzigTijdslot(int id, int tijdslotid, IFormCollection collection)
        {
            var huidigtijdslot = _context.Tijdslot.Find(tijdslotid); 
            var tijdsloten = _context.AlleVrijeTijdsloten();

            var nieuwTijdslotId = int.Parse(collection["Tijdslot"]); 
            var nieuwTijdSlot = _context.AlleVrijeTijdsloten().Result.Find(nt => nt.Id == nieuwTijdslotId); 

            var bestelling = _context.Bestellingen.Include("Tijdslot").ToList().Find(b => b.Id == id);

            huidigtijdslot.IsVrij = true;
            nieuwTijdSlot.IsVrij = false; 
            bestelling.Tijdslot = nieuwTijdSlot;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index)); 
        }

        // GET: Bestelling/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            
            //var bestelling = _context.Bestellingen.Include("Tijdslot").ToList().Find(g => g.Id == id);
            var bestelling = await _context.Bestellingen
                .Include(b => b.Tijdslot)
                .Include(b => b.GerechtenLijst)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bestelling == null)
            {
                return NotFound();
            }

            //Check welke gebruiker request doet vervolgens nakijken of tijdslot verstreken is
            if (!(User.IsInRole(RollenEnum.Admin.ToString()) || User.IsInRole(RollenEnum.Kassamedewerker.ToString())))
            {
                if (DateTime.Now > bestelling.Tijdslot.Tijdstip.AddHours(-1))
                {
                    return RedirectToAction(nameof(Index));
                }
            }


            //_context.Tijdslot.Include("InGebruikDoorKok").ToList().Find(tijdslot => tijdslot.Tijdstip == bestelling.Tijdslot.Tijdstip).IsVrij = true;
            ViewData["HuidigeKlant"] = _context.GebruikersMetRolKlant().Find(k=> k.Id == bestelling.KlantId); 
            ViewData["Klanten"] = new SelectList(_context.GebruikersMetRolKlant(), "Id", "UserName");
            ViewData["AlleGerechtenNamen"] = new SelectList(_context.Gerechten.Include("Bestellingen").Include("VoorkeursgerechtenVanKlanten").Include("Categorie"), "Naam", "Naam");
            ViewData["Tijdslot"] = new SelectList(_context.AlleVrijeTijdsloten().Result, "Tijdstip", "Tijdstip");
            return View(bestelling);
        }

        // POST: Bestelling/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

Lekkerbek.Web/Views/Bestelling/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@using System.Linq
@using Lekkerbek.Web.Models.Identity
@model Lekkerbek.Web.ViewModels.Bestelling.CreateViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Bestelling</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (User.IsInRole(RollenEnum.Admin.ToString()) || User.IsInRole(RollenEnum.Kassamedewerker.ToString()))
            {
                @*<div class="form-group">
                    <label asp-for="Klant" class="control-label"></label>
                    <select asp-for="Klant" class="form-control" asp-items="ViewBag.Klanten"></select>
                </div>*@
                <div class="form-group">
                    @Html.DropDownListFor(m => m.KlantId, Model.KlantenLijst)
                </div>
            }
            <div class="form-group">
            <label asp-for="Opmerkingen" class="control-label"></label>
            <input asp-for="Opmerkingen" class="form-control" />
            <span asp-validation-for="Opmerkingen" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AantalMaaltijden" class="control-label"></label>
            <input asp-for="AantalMaaltijden" class="form-control" />
            <span asp-validation-for="AantalMaaltijden" class="text-danger"></span>
        </div>



            @*<div class="form-group">
            <label asp-for="Klant.UserName" class="control-label"></label>
            <select asp-for="Klant.UserName" class="form-control" asp-items="ViewBag.Klanten"></select>
        </div>*@
            <div class="form-group">
                <label asp-for="GerechtenNamen" class="control-label"></label>
                <select asp-for="GerechtenNamen" class="form-control" asp-items="Model.GerechtenLijst" multiple="multiple"></select>
            </div>
            <div class="form-group">
                <label asp-for="Tijdstip" class="control-label"></label>
                <select asp-for="Tijdstip" class="form-control" asp-items="Model.Tijdsloten"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Maak bestelling" class="btn btn-primary" />
            </div>
        </form>
</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Bestelling/Delete.cshtml
@model Lekkerbek.Web.Models.Bestelling

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bestelling</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tijdslot.Tijdstip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tijdslot.Tijdstip)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lekkerbek.Web/Views/Bestelling/Details.cshtml
@using Lekkerbek.Web.Models.Identity
@model Lekkerbek.Web.Models.Bestelling

@{
    ViewData["Title"] = "Factuur";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Factuur</h1>

<div>
    <h4>Bestelling</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Opmerkingen)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Opmerkingen)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AantalMaaltijden)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AantalMaaltijden)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Klant)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Klant.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tijdslot.Tijdstip)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tijdslot.Tijdstip)
        </dd>
        <dt class="col-sm-2">
            Status
        </dt>
        @if (Model.Tijdslot.InGebruikDoorKok != null)
        {
            if (Model.IsAfgerond)
            {
                <dd class="col-sm-10">
                    Bestelling afgerond
                </dd>

            }
            else
            {
                <dd class="col-sm-10">
                    In bereiding
                </dd>

            }
        }
        else
        {
            <dd class="col-sm-10">
                Bestelling geplaatst
            </dd>
        }
    </dl>
    <h4>
        @Html.DisplayNameFor(model => model.GerechtenLijst)
    </h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GerechtenLijst.First().Naam)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GerechtenLijst.First().Categorie)
                </th>
                <th>
                    Prijs excl. btw*
                </th>
                <th>
                    Prijs Incl. btw*
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Gerecht gerecht in Model.GerechtenLijst)
            {
                <tr>
                    <td>
                        @gerecht.Naam
                    </td>
                    <td>
                        @gerecht.CategorieId
                    </td>
                    <td>
                        @gerecht.Prijs
                    </td>
                    <td>
                        @gerecht.PrijsInclBtw()
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <dl class="row">
        @*<dt class="col-sm-2">
            Korting*
        </dt>
        <dd class="col-sm-10">
            @{
                var korting = Math.Round(((double)ViewBag.TotaalPrijsInclBtw - (double)ViewBag.TotaalPrijs),2);

            }
            @korting
        </dd>*@
        <dt class="col-sm-2">
            Totaal excl. btw*
        </dt>
        <dd class="col-sm-10">
            @ViewBag.TotaalPrijs
        </dd>
        <dt class="col-sm-2">
            Totaal incl. btw*
        </dt>
        <dd class="col-sm-10">
            @ViewBag.TotaalPrijsInclBtw
        </dd>

    </dl>
</div>
<p>* Prijzen in euro</p>
<div>
    @if (!Model.IsAfgerond)
    {
    @if ((User.IsInRole(RollenEnum.Admin.ToString()) || User.IsInRole(RollenEnum.Kassamedewerker.ToString())) && Model.Tijdslot.InGebruikDoorKok != null)
    {
        <form asp-controller="Bestelling" asp-action="Afronden" asp-route-id="@Model.Id">
            <input type="submit" value="Bestelling afronden" />
        </form>
    }
    }

</div>
<div>

    <button onclick="window.print();return false;" class="btn-primary" value="Afdrukken">Afdrukken</button>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>

</div>

Lekkerbek.Web/Views/Bestelling/Edit.cshtml
@model Lekkerbek.Web.ViewModels.Bestelling.EditViewModel

@using Lekkerbek.Web.Models.Identity 

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>
<h4>Bestelling</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.bestelling.Id" />
            <div class="form-group">
                <label asp-for="@Model.bestelling.Id" class="control-label"></label>
                <input asp-for="@Model.bestelling.Id" class="form-control" readonly="readonly"/>
                <span asp-validation-for="@Model.bestelling.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.bestelling.Opmerkingen" class="control-label"></label>
                <input asp-for="@Model.bestelling.Opmerkingen" class="form-control" />
                <span asp-validation-for="@Model.bestelling.Opmerkingen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.bestelling.AantalMaaltijden" class="control-label"></label>
                <input asp-for="@Model.bestelling.AantalMaaltijden" class="form-control" />
                <span asp-validation-for="@Model.bestelling.AantalMaaltijden" class="text-danger"></span>
            </div>
            @if (User.IsInRole(RollenEnum.Admin.ToString()) || User.IsInRole(RollenEnum.Kassamedewerker.ToString()))
            {
                <div class="form-group">
                    <p>Huidige klant van deze bestelling: @Model.HuidigeKlant</p>
                    @Html.DropDownListFor(k => k.KlantId, Model.Klanten)
                </div>
            }
            <div>
                <p>Tijdslot</p>
                <p>@Model.bestelling.Tijdslot.Tijdstip</p><a asp-action="WijzigTijdslot" asp-route-id="@Model.bestelling.Id" asp-route-tijdslotId="@Model.bestelling.Tijdslot.Id" class="btn btn-primary">Verander het tijdslot</a>
            </div>

            <div class="form-group" style="padding-top:10px">
                <input type="submit" value="Opslaan" class="btn btn-primary" />
                <a asp-action="VoegGerechtenToe" asp-route-id="@Model.bestelling.Id" class="btn btn-primary">Voeg een gerecht toe</a>

            </div>
        </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.bestelling.GerechtenLijst.First().Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bestelling.GerechtenLijst.First().Categorie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bestelling.GerechtenLijst.First().Prijs)
            </th>
            <th>
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var gerecht in Model.bestelling.GerechtenLijst)
        {
            <tr>
                <td>
                    @gerecht.Naam
                </td>
                <td>
                    @gerecht.CategorieId
                </td>
                <td>
                    € @gerecht.Prijs
                </td>
                <td>
                    <a asp-action="VerwijderEenGerecht" asp-route-gerechtNaam="@gerecht.Naam" asp-route-bestellingid="@Model.bestelling.Id"}>Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Bestelling/MijnBestellingen.cshtml
@model IEnumerable<Lekkerbek.Web.Models.Bestelling>

@{
    ViewData["Title"] = "MijnBestellingen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>MijnBestellingen</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opmerkingen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AantalMaaltijden)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tijdslot)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opmerkingen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AantalMaaltijden)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tijdslot)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>