Lekkerbek.Web/ViewModels/Bestelling/CreateViewModel.cs
using Lekkerbek.Web.Models;
using Lekkerbek.Web.Models.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lekkerbek.Web.ViewModels.Bestelling
{
    [NotMapped]
    public class CreateViewModel
    {
        //public List<Gebruiker> Klanten { get; set; }
        public IEnumerable<SelectListItem> KlantenLijst { get; set; }
        public int KlantId { get; set; }
        public IEnumerable<SelectListItem> GerechtenLijst { get; set; }
        [Required]
        [DisplayName("Aantal maaltijden")]
        public IEnumerable<string> GerechtenNamen { get; set; }
        public IEnumerable<SelectListItem> Tijdsloten{ get; set; }
        public DateTime Tijdstip{ get; set; }
        [Range(1, 999)]
        public int AantalMaaltijden { get; set; }
        public string Opmerkingen { get; set; }
    }
}

Lekkerbek.Web/Controllers/KlachtenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.Web.Context;
using Lekkerbek.Web.Models;
using Lekkerbek.Web.Models.Identity;
using Lekkerbek.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using static Lekkerbek.Web.Models.Identity.RollenEnum;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Admin,Klant")]
    public class KlachtenController : Controller
    {
        private readonly IKlachtenService _klachtenService;
        private readonly IGebruikerService _gebruikerService;
        private readonly IMailService _mailService;
        private readonly UserManager<Gebruiker> _userManager;

        private readonly List<string> _blackList = new List<string>()
        {
            "henk.verelst@thix-it.be","henk.verelst@ucll.be","info@lekkerbek.be"
        };

        public KlachtenController(IKlachtenService klachtenService, UserManager<Gebruiker> userManager, IGebruikerService gebruikerService, IMailService mailService)
        {
            _klachtenService = klachtenService;
            _userManager = userManager;
            _gebruikerService = gebruikerService;
            _mailService = mailService;
        }

        // GET: Klachten
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole(RollenEnum.Klant.ToString()))
            {
                var currentUser = _gebruikerService.GetGebruikerInfo(await _userManager.GetUserAsync(HttpContext.User));
                return View(_klachtenService.GetKlachtenVanKlant(currentUser.Id));
            }
            else
            {
                return View(_klachtenService.GetKlachten());
            }
        }

        // GET: Klachten/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klacht = _klachtenService.GetKlacht((int)id);
            if (klacht == null)
            {
                return NotFound();
            }

            return View(klacht);
        }
        [Authorize(Roles = "Klant")]
        // GET: Klachten/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Klachten/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Klant")]
        public async Task<IActionResult> Create([Bind("Id,Onderwerp,Omschrijving")] Klacht klacht)
        {
            if (ModelState.IsValid)
            {
                var currentUser = _gebruikerService.GetGebruikerInfo(await _userManager.GetUserAsync(HttpContext.User));
                klacht.Klant = currentUser;
                await _klachtenService.AddKlacht(klacht);
                var admins = _gebruikerService.GetGebruikers().Where(gebruiker =>
                    _gebruikerService.GetHoogsteRolVanGebruiker(gebruiker.Id)
                        .Equals(RollenEnum.Admin.ToString())).ToList();
                List<Gebruiker> editedAdmins = new List<Gebruiker>();
                editedAdmins.AddRange(collection: admins);
                foreach (var admin in admins)
                {
                    if (_blackList.Contains(admin.Email)&& DateTime.Now < new DateTime(2021,06,15))
                    {
                        editedAdmins.Remove(admin);
                    }
                }

                await _mailService.SendKlacht(klacht, editedAdmins);
                return RedirectToAction(nameof(Index));
            }
            return View(klacht);
        }

        // GET: Klachten/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var klacht = _klachtenService.GetKlacht((int)id);
            if (klacht == null)
            {
                return NotFound();
            }

            return View(klacht);
        }

        // POST: Klachten/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var klacht = _klachtenService.GetKlacht((int)id);
            await _klachtenService.DeleteKlacht(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: Klachten/RondAf/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RondAf(int id)
        {
            if (User.IsInRole(RollenEnum.Admin.ToString()))
            {
                try
                {
                    await _klachtenService.RondKlachtAf(id);
                    var admins = _gebruikerService.GetGebruikers().Where(gebruiker =>
                        _gebruikerService.GetHoogsteRolVanGebruiker(gebruiker.Id)
                            .Equals(RollenEnum.Admin.ToString())).ToList();
                    List<Gebruiker> editedAdmins = new List<Gebruiker>();
                    editedAdmins.AddRange(collection: admins);
                    foreach (var admin in admins)
                    {
                        if (_blackList.Contains(admin.Email) && DateTime.Now < new DateTime(2021, 06, 15))
                        {
                            editedAdmins.Remove(admin);
                        }
                    }

                    await _mailService.SendKlachtAfgehandeld(_klachtenService.GetKlacht(id));
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
            }
            return RedirectToAction(nameof(Details), new { id = id });
        }
    }
}

Lekkerbek.Web/Views/Klachten/Create.cshtml
@model Lekkerbek.Web.Models.Klacht

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Klacht indienen</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Onderwerp" class="control-label"></label>
                <input asp-for="Onderwerp" class="form-control" />
                <span asp-validation-for="Onderwerp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Omschrijving" class="control-label"></label>
                <input asp-for="Omschrijving" class="form-control" />
                <span asp-validation-for="Omschrijving" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/Klachten/Delete.cshtml
@model Lekkerbek.Web.Models.Klacht

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Klacht</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tijdstip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tijdstip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Onderwerp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Onderwerp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Omschrijving)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Omschrijving)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lekkerbek.Web/Views/Klachten/Details.cshtml
@using Lekkerbek.Web.Models.Identity
@model Lekkerbek.Web.Models.Klacht

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Klacht</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tijdstip)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tijdstip)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Onderwerp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Onderwerp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Omschrijving)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Omschrijving)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Klant.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Klant.UserName)
        </dd>
        <dt class="col-sm-2">
            Status
        </dt>
        @if (Model.IsAfgehandeld)
            {
                <dd class="col-sm-10">Afgehandeld</dd>
            }
            else
            {
                <dd class="col-sm-10">In behandeling</dd>
            }
    </dl>
</div>
<div>
    @if (!Model.IsAfgehandeld)
    {
        @if (User.IsInRole(RollenEnum.Admin.ToString()))
        {
            <form asp-controller="Klachten" asp-action="RondAf" asp-route-id="@Model.Id">
                <input type="submit" value="Klacht afhandelen" />
            </form>
        }
    }

</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Lekkerbek.Web/Views/Klachten/Index.cshtml
@using Lekkerbek.Web.Models.Identity
@model IEnumerable<Lekkerbek.Web.Models.Klacht>



@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

@if (User.IsInRole(RollenEnum.Klant.ToString()))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tijdstip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Onderwerp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Klant.Id)
        </th>
        <th>
            Status
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        
        <tr>
            @if (!item.IsAfgehandeld && DateTime.Now > item.Tijdstip.AddDays(7))
            {
                
                <td class="alert-danger">
                    @Html.DisplayFor(modelItem => item.Id)
                </td>

                <td class="alert-danger">
                    @Html.DisplayFor(modelItem => item.Tijdstip)
                </td>
                <td class="alert-danger">
                    @Html.DisplayFor(modelItem => item.Onderwerp)
                </td>
                <td class="alert-danger">
                    @Html.DisplayFor(modelItem => item.Klant.Id)
                </td>
                <td class="alert-danger">
                    @{
                        string status = item.IsAfgehandeld ? "Afgehandeld" : "In behandeling";
                    }
                    @status
                </td>
                <td class="alert-danger">
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            }
            else
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Tijdstip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Onderwerp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Klant.Id)
                </td>
                <td>
                    @{
                        string status = item.IsAfgehandeld ? "Afgehandeld" : "In behandeling";
                    }
                    @status
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            }

        </tr>
    }
    </tbody>
</table>