Lekkerbek.Web/Models/Kalender/OpeningsUur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Lekkerbek.Web.Models.Kalender
{
    public class OpeningsUur : ITijdInvulling
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [RegularExpression("(Maandag)|(Dinsdag)|(Woensdag)|(Donderdag)|(Vrijdag)|(Zaterdag)|(Zondag)", ErrorMessage = "Geen dag van de week")]
        public string Dag { get; set; }
        //[RegularExpression("(([0-1][0-9]|[2][0-3]):[0-5][0-9]-([0-1][0-9]|[2][0-4]):[0-5][0-9])|(Gesloten)", ErrorMessage = "Ongeldig tijdstip juiste formaat is xx:xx-xx:xx")]
        [DisplayName("Openingsuren")]
        public string Uur => IsGesloten ? (SluitingsUur.Date + "").Substring(0, 10) + ": Gesloten" : Startuur + " - " + SluitingsUur.TimeOfDay;
        [DisplayName("Sluitingsdag")]
        public bool IsGesloten { get; set; } = false;
        [Required]
        public DateTime Startuur { get; set; }
        [Required]
        public DateTime SluitingsUur { get; set; }

        public List<DateTime> AlleUren()
        {
            List<DateTime> alleUren = new List<DateTime>();
            for(int i= 0; i < SluitingsUur.Hour; i++)
            {
                alleUren.Add(Startuur.AddHours(i));
            }
            return alleUren; 

        }
    }
}

Lekkerbek.Web/Models/OpeningsUur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Lekkerbek.Web.Models
{
    public class OpeningsUur : ITijdInvulling
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [RegularExpression("(Maandag)|(Dinsdag)|(Woensdag)|(Donderdag)|(Vrijdag)|(Zaterdag)|(Zondag)", ErrorMessage = "Geen dag van de week")]
        public string Dag { get; set; }
        //[RegularExpression("(([0-1][0-9]|[2][0-3]):[0-5][0-9]-([0-1][0-9]|[2][0-4]):[0-5][0-9])|(Gesloten)", ErrorMessage = "Ongeldig tijdstip juiste formaat is xx:xx-xx:xx")]
        [DisplayName("Openingsuren")]
        public string Uur => IsGesloten ? (SluitingsUur.Date + "").Substring(0, 10) + ":\t\tGesloten" : Startuur + " - " + SluitingsUur.TimeOfDay;
        [DisplayName("Sluitingsdag")]
        public bool IsGesloten { get; set; } = false;
        [Required]
        public DateTime Startuur { get; set; }
        [Required]
        public DateTime SluitingsUur { get; set; }

        public List<DateTime> AlleUren()
        {
            List<DateTime> alleUren = new List<DateTime>();
            for(int i= 0; i < SluitingsUur.Hour; i++)
            {
                alleUren.Add(Startuur.AddHours(i));
            }
            return alleUren; 

        }
    }
}

Lekkerbek.Web/ViewModels/Bestelling/CreateViewModel.cs
using Lekkerbek.Web.Models;
using Lekkerbek.Web.Models.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lekkerbek.Web.ViewModels.Bestelling
{
    [NotMapped]
    public class CreateViewModel
    {
        //public List<Gebruiker> Klanten { get; set; }
        public IEnumerable<SelectListItem> KlantenLijst { get; set; }
        public int KlantId { get; set; }
        public IEnumerable<SelectListItem> GerechtenLijst { get; set; }
        [Required]
        [DisplayName("Aantal maaltijden")]
        public IEnumerable<string> GerechtenNamen { get; set; }
        public IEnumerable<SelectListItem> Tijdsloten{ get; set; }
        public DateTime Tijdstip{ get; set; }
        [Range(1, 999)]
        public int AantalMaaltijden { get; set; }
        public string Opmerkingen { get; set; }
    }
}

Lekkerbek.Web/ViewModels/OpeningsUur/AfwezigheidKokViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Security.AccessControl;
using System.Threading.Tasks;

namespace Lekkerbek.Web.ViewModels.OpeningsUur
{
    public class AfwezigheidKokViewModel
    {
        public int KokId { get; set; }
        [DisplayName("Is kok ziek?")]
        public bool IsZiek { get; set; }
        public int OpeningsUurId { get; set; }
    }
}

Lekkerbek.Web/Controllers/OpeningsUurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.Web.Context;
using Lekkerbek.Web.Models;
using Lekkerbek.Web.Models.Kalender;
using Lekkerbek.Web.Services;
using Lekkerbek.Web.ViewModels.OpeningsUur;
using Microsoft.AspNetCore.Authorization;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OpeningsUurController : Controller
    {
        private readonly IKalenderService _kalenderService;
        private readonly IGebruikerService _gebruikerService;

        public OpeningsUurController(IKalenderService kalenderService, IGebruikerService gebruikerService)
        {
            _kalenderService = kalenderService;
            _gebruikerService = gebruikerService;
        }

        // GET: OpeningsUur
        public  IActionResult Index()
        {
            var model = _kalenderService.GetOpeningsUren().AsEnumerable();
                        
            return View(model);
        }

        // GET: OpeningsUur/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var openingsUur = _kalenderService.GetOpeningsUren()
                .FirstOrDefault(m => m.Id == id);
            if (openingsUur == null)
            {
                return NotFound();
            }

            return View();
        }

        // GET: OpeningsUur/Details/5
        public async Task<IActionResult> DagInfo(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var openingsUren = _kalenderService.GetOpeningsUur(id);

            if(openingsUren!=null && !openingsUren.IsGesloten)
            {
                var datum = openingsUren.Startuur.Date;
                var tijdslotenVanDag = _kalenderService.GetTijdslotenOpDag(datum);
            
                DagInfoViewModel vm = new DagInfoViewModel()
                {
                    OpeningsUur = openingsUren,
                    AantalKoksBeschikbaar = _kalenderService.AantalKoksBeschikbaarOpDatum(datum),
                    KoksVakantieOpDag = _kalenderService.GetGebruikersMetVerlofOpDatum(datum),
                    KoksZiekOpDag = _kalenderService.GetGebruikersZiekOpDatum(datum),
                    Tijdsloten = tijdslotenVanDag,
                    AlleKoks = _gebruikerService.GetGebruikersMetRolKok().ToList()
                };
                return View(vm);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> IsZiekOfOpVerlof(int id,[Bind("IsZiek, OpeningsUurId")] AfwezigheidKokViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var datum = _kalenderService.GetOpeningsUren().FirstOrDefault(uur => uur.Id == vm.OpeningsUurId).Startuur;
                if (vm.IsZiek)
                {
                    var ziektedagen = _kalenderService.GetZiekteDagenVanGebruiker(id);
                        ziektedagen.Dagen.Add(new Dag() { Datum = datum });
                    await _kalenderService.UpdateZiekteDagenVanGebruiker(ziektedagen);
                }
                else
                {
                    var verlofdagen = _kalenderService.GetVerlofDagenVanGebruiker(id);
                    verlofdagen.Dagen.Add(new Dag() { Datum = datum });
                    await _kalenderService.UpdateVerlofDagenVanGebruiker(verlofdagen);
                }
                return RedirectToAction(nameof(DagInfo),new{vm.OpeningsUurId});
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: OpeningsUur/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: OpeningsUur/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Dag,Uur,IsGesloten,Startuur,SluitingsUur")] OpeningsUur openingsUur)
        {
            if (ModelState.IsValid && openingsUur.Startuur.Date == openingsUur.SluitingsUur.Date)
            {
                await _kalenderService.AddOpeningsUur(openingsUur);
                return RedirectToAction(nameof(Index));
            }
            return View(openingsUur);
        }
        /*
        // GET: OpeningsUur/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var openingsUur = _kalenderService.GetOpeningsUren()
                .FirstOrDefault(m => m.Id == id);
            if (openingsUur == null)
            {
                return NotFound();
            }
            return View(openingsUur);
        }*/
        
       
        /*
        // POST: OpeningsUur/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Dag,Uur,IsGesloten,Startuur,SluitingsUur")] OpeningsUur openingsUur)
        {
            if (id != openingsUur.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _kalenderService.UpdateOpeningsUren(openingsUur);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(openingsUur);
        }*/

        /*// GET: OpeningsUur/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var openingsUur = _kalenderService.GetOpeningsUren()
                .FirstOrDefault(m => m.Id == id);
            if (openingsUur == null)
            {
                return NotFound();
            }

            return View(openingsUur);
        }

        // POST: OpeningsUurs/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var openingsUur = _kalenderService.GetOpeningsUren()
                .FirstOrDefault(m => m.Id == id);
            _kalenderService.de
            return RedirectToAction(nameof(Index));
        }*/
    }
}

Lekkerbek.Web/Controllers/TijdslotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.Web.Context;
using Lekkerbek.Web.Models;
using Lekkerbek.Web.Models.Identity;
using Lekkerbek.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Lekkerbek.Web.Controllers
{
    [Authorize(Roles = "Admin,Kassamedewerker,Kok")]
    public class TijdslotController : Controller
    {
        private readonly ITijdslotService _tijdslotService;
        private readonly IBestellingService _bestellingService;
        private readonly RoleManager<Role> _roleManager;
        private readonly UserManager<Gebruiker> _userManager;

        public TijdslotController(IdentityContext context, RoleManager<Role> roleManager,
            UserManager<Gebruiker> userManager, ITijdslotService tijdslotService, IBestellingService bestellingService)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _tijdslotService = tijdslotService;
            _bestellingService = bestellingService;
        }

        // GET: Tijdslot

        public async Task<IActionResult> Index()
        {
            if (User.IsInRole(RollenEnum.Kok.ToString()))
            {
                var currentUser = (await _userManager.GetUserAsync(HttpContext.User));
                var tijdsloten = _tijdslotService.GetTijdslotenVanKok(currentUser.Id);
                return View(tijdsloten.OrderBy(tijdslot => tijdslot.Tijdstip));
            }
            else
            {
                return View(_tijdslotService.GetAlleTijdsloten().OrderBy(tijdslot => tijdslot.Tijdstip));
            }
        }

        // GET: Tijdslot/Details/5

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tijdslot = _tijdslotService.GetTijdslot((int) id);
            if (tijdslot == null)
            {
                return NotFound();
            }

            ViewBag.Bestelling =(await _bestellingService.GetAlleBestellingen()).FirstOrDefault(bestelling => bestelling.Tijdslot.Id == id);
            return View(tijdslot);
        }

        [Authorize(Roles = "Admin,Kassamedewerker")]
        // GET: Tijdslot/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tijdslot/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Kassamedewerker")]
        public async Task<IActionResult> Create([Bind("Id,Tijdstip,IsVrij")] Tijdslot tijdslot)
        {
            if (ModelState.IsValid)
            {
                await _tijdslotService.AddTijdslot(tijdslot);
                return RedirectToAction(nameof(Index));
            }

            return View(tijdslot);
        }

        // POST: Tijdslot/Toegewezen/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Kok")]
        public async Task<IActionResult> Toegewezen(int id)
        {
            try
            {
                var tijdslot = _tijdslotService.GetTijdslot(id);
                if (tijdslot.InGebruikDoorKok == null)
                    tijdslot.InGebruikDoorKok = await _userManager.GetUserAsync(HttpContext.User);
                await _tijdslotService.UpdateTijdslot(tijdslot);
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }

            return RedirectToAction(nameof(Details), new {id});
        }


        // GET: Tijdslot/Edit/5
        [Authorize(Roles = "Admin,Kassamedewerker")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tijdslot = _tijdslotService.GetTijdslot((int) id);
            if (tijdslot == null)
            {
                return NotFound();
            }

            return View(tijdslot);
        }

        // POST: Tijdslot/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Kassamedewerker")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tijdstip,IsVrij")] Tijdslot tijdslot)
        {
            if (id != tijdslot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _tijdslotService.UpdateTijdslot(tijdslot);
                }
                catch (DbUpdateConcurrencyException)
                {

                    throw;

                }

                return RedirectToAction(nameof(Index));
            }

            return View(tijdslot);
        }

        // GET: Tijdslot/Delete/5
        [Authorize(Roles = "Admin,Kassamedewerker")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tijdslot = _tijdslotService.GetTijdslot((int) id);
            if (tijdslot == null)
            {
                return NotFound();
            }

            return View(tijdslot);
        }

        // POST: Tijdslot/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Kassamedewerker")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _tijdslotService.DeleteTijdslot(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

Lekkerbek.Web/Views/OpeningsUur/Create.cshtml
@model OpeningsUur

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>OpeningsUur</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Dag" class="control-label"></label>
                <input asp-for="Dag" class="form-control" />
                <span asp-validation-for="Dag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsGesloten" class="control-label"></label>
                <input asp-for="IsGesloten" class="checkbox" name="IsGesloten" />
                <span asp-validation-for="IsGesloten" class="text-danger"></span>
            </div>
            @*<script>
                $(document).ready(function () {
                    $('input[name="IsGesloten"]').change(function () {
                        if ($(this).val()) {
                            $(document.getElementById("start")).hide();
                            $(document.getElementById("start")).hide();
                        }
                    });
                });
            </script>*@
            <div class="form-group" id="start">
                <label asp-for="Startuur" class="control-label"></label>
                <input asp-for="Startuur" class="form-control" />
                <span asp-validation-for="Startuur" class="text-danger"></span>
            </div>
            <div class="form-group" id="sluiting">
                <label asp-for="SluitingsUur" class="control-label"></label>
                <input asp-for="SluitingsUur" class="form-control" />
                <span asp-validation-for="SluitingsUur" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <p>Indien gesloten gelieve beide data alsnog in te vullen</p>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/OpeningsUur/DagInfo.cshtml
@using Microsoft.CodeAnalysis.Differencing
@model Lekkerbek.Web.ViewModels.OpeningsUur.DagInfoViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Info @Model.OpeningsUur.Dag @Model.OpeningsUur.Startuur.Date.ToString().Substring(0, 10)</h2>

<h4>Aantal koks beschikbaar</h4>
<p>@Model.AantalKoksBeschikbaar</p>
@if(Model.AlleKoks.Count >0){
<h4>Overzicht koks</h4>
    
    <table class="table">
        <thead>
            <tr>
                <th>
                    Gebruikersnaam
                </th>
                <th>
                    Beschikbaarheid
                </th>
                <th>

                </th>
                <th>

                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AlleKoks)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                @if (Model.KoksZiekOpDag.Contains(item))
                {
                    <td>
                        Is ziek
                    </td>
                }
                else if (Model.KoksVakantieOpDag.Contains(item))
                {
                    <td>
                        Heeft vakantie
                    </td>

                }
                else
                {
                    <td>
                        Beschikbaar
                    </td>
                    <td>
                        <form asp-controller="OpeningsUur" asp-action="IsZiekOfOpVerlof" asp-route-id="item.Id" asp-route-IsZiek="true" asp-route-OpeningsUurId="@Model.OpeningsUur.Id">
                            <input type="submit" value="Ziek melden" />
                        </form>
                        <form asp-controller="OpeningsUur" asp-action="IsZiekOfOpVerlof" asp-route-id="item.Id" asp-route-IsZiek="false" asp-route-OpeningsUurId="@Model.OpeningsUur.Id">
                            <input type="submit" value="Vakantie melden" />
                        </form>
                    </td>
                }
                <td>
                    <a asp-controller="Account" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}



<table class="table">
    <thead>
        <tr>
            <th>
                Tijdstip
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tijdsloten.FirstOrDefault().Id)
            </th>
            <th>
                Toegewezen aan kok
            </th>
            <th>
                Vrij
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Tijdsloten)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Tijdstip.TimeOfDay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InGebruikDoorKok.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsVrij)
                </td>
                <td>
                    <a asp-controller="Tijdslot" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="Tijdslot" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Lekkerbek.Web/Views/OpeningsUur/Delete.cshtml
@*
@model Lekkerbek.Web.Models.OpeningsUur

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OpeningsUur</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Uur)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
*@

Lekkerbek.Web/Views/OpeningsUur/Details.cshtml
@model Lekkerbek.Web.ViewModels.OpeningsUur.OpeningsUurViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OpeningsUur</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Uur)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lekkerbek.Web/Views/OpeningsUur/Edit.cshtml
@model OpeningsUur

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>OpeningsUur</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Dag" class="control-label"></label>
                <input asp-for="Dag" class="form-control" readonly />
                <span asp-validation-for="Dag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsGesloten" class="control-label"></label>
                <input asp-for="IsGesloten" class="checkbox" />
                <span asp-validation-for="IsGesloten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Startuur" class="control-label"></label>
                <input asp-for="Startuur" class="form-control" />
                <span asp-validation-for="Startuur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SluitingsUur" class="control-label"></label>
                <input asp-for="SluitingsUur" class="form-control" />
                <span asp-validation-for="SluitingsUur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.Web/Views/OpeningsUur/Index.cshtml
@model IEnumerable<OpeningsUur>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="btn btn-primary" asp-controller="OpeningsUur" asp-action="Create">Nieuwe Dag Aanmaken</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Dag)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Uur)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="DagInfo" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Dag)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Uur)
                </td>
                @*<td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>*@
            </tr>
        }
    </tbody>
</table>